name: QIT Weekly Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2'

permissions:
  contents: read

jobs:
  build:
    name: Build artifact for weekly QIT
    uses: ./.github/workflows/build.yml
    with:
      plugin_name: woocommerce-shipping-dhl

  qit:
    name: Run weekly QIT against packaged artifact
    needs: build
    uses: ./.github/workflows/qit_runner.yml
    with:
      extension: woocommerce-shipping-dhl
      artifact: ${{ needs.build.outputs.plugin_name }}
      wp-version: stable
      wc-version: stable
      php-version: '8.1'
      test-activation: 'true'
      test-phpcompatibility: 'true'
      test-phpstan: 'true'
      test-plugin-check: 'true'
      test-security: 'false'
      options: ''
    secrets:
      PARTNER_USER: ${{ secrets.PARTNER_USER }}
      PARTNER_SECRET: ${{ secrets.PARTNER_SECRET }}
